config/routes.rb
Cogsurver::Application.routes.draw do
  # api
  namespace :api do
    resources :users, 
              :travel_fixes, 
              :landmarks, 
              :landmark_visits, 
              :direction_distance_estimates, 
              :regions, 
              :log_entries,
              :gps_accuracy_measures,
              :compass_accuracy_measures,
              :studies,
              :tsp_games
  end
  
  # site
  root :to => 'site#land'
  
  # viewer
  match '/viewer', :to => 'viewer#main', :as => :viewer_main
  
  # study (for DissStudyThree)
  match '/study', :to => 'study#checklist', :as => :study_checklist
  match '/study/consent', :to => 'study#consent', :as => :study_consent
  match '/study/demographics', :to => 'study#demographics', :as => :study_demographics
  match '/study/sbsod', :to => 'study#sbsod', :as => :study_sbsod
  match '/study/landmarks', :to => 'study#landmarks', :as => :study_landmarks
  match '/study/final', :to => 'study#final', :as => :study_final
  
  # sign in/sign out
  devise_for :users
end

app/models/study.rb
class Study < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  validates :name, :presence => true
end

app/controllers/api/studies_controller.rb
class Api::StudiesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /studies.xml
  def index
    if current_user
      @studies = current_user.studies
    end
    
    json = @studies.to_json
    
    if current_user.roles.where(:title => 'admin').length > 0
      @studies = Study.all
      json = @studies.to_json(:include => :users)
    end
    
    respond_to do |format|
      format.xml  { render :xml => @studies }
      format.json { render :json => json }
    end
  end

  # GET /studies/1.xml
  def show
    @study = Study.find(params[:id])

    respond_to do |format|
      format.xml  { render :xml => @study }
    end
  end

  # POST /studies.xml
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        flash[:notice] = 'Study was successfully created.'
        format.xml  { render :xml => @study, :status => :created, :location => api_study_url(@study) }
      else
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /studies/1.xml
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        flash[:notice] = 'Study was successfully updated.'
        format.xml  { render :xml => @study }
      else
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1.xml
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      format.xml  { head :ok }
    end
  end
end

app/controllers/study_controller.rb
class StudyController < ApplicationController
  def checklist
    redirect_to study_consent_path if !current_user.gave_consent
  end
  
  def consent
    if request.post?
      user = current_user
      user.gave_consent = Time.now
      if user.save()
        flash[:message] = "Thank you for agreeing to participate."
        redirect_to study_checklist_path
      end
    end
  end
  
  def demographics
    if request.get?
      @dissstudythree_demographics_questionnaire = DissstudythreeDemographicsQuestionnaire.new
      
    elsif request.post?
      @dissstudythree_demographics_questionnaire = DissstudythreeDemographicsQuestionnaire.new(params[:dissstudythree_demographics_questionnaire])
      @dissstudythree_demographics_questionnaire.user = current_user
      
      respond_to do |format|
        if @dissstudythree_demographics_questionnaire.save
          flash[:message] = "Thank you for completing the demographics questionnaire."
          format.html { redirect_to(study_checklist_path) }
        else
          flash[:error] = "There was an error saving your demographics questionnaire. Did you answer all the questions?"
          format.html {}
        end
      end
    end
  end
  
  def sbsod
    if request.get?
      @sbsod_record = SbsodRecord.new
      
    elsif request.post?
      @sbsod_record = SbsodRecord.new(params[:sbsod_record])
      @sbsod_record.user = current_user
      
      respond_to do |format|
        if @sbsod_record.save
          flash[:message] = "Thank you for completing the sense of direction questionnaire."
          format.html { redirect_to(study_checklist_path) }
        else
          flash[:error] = "There was an error saving your sense of direction questionnaire. Did you answer all the questions?"
          format.html {}
        end
      end
    end
  end
  
  def landmarks
    
  end
  
  def final
    if request.get?
      @dissstudythree_final_questionnaire = DissstudythreeFinalQuestionnaire.new
      
    elsif request.post?
      @dissstudythree_final_questionnaire = DissstudythreeFinalQuestionnaire.new(params[:dissstudythree_final_questionnaire])
      @dissstudythree_final_questionnaire.user = current_user
      
      respond_to do |format|
        if @dissstudythree_final_questionnaire.save
          flash[:message] = "Thank you for completing the final questionnaire."
          format.html { redirect_to(study_checklist_path) }
        else
          flash[:error] = "There was an error saving your final questionnaire. Did you answer all the questions?"
          format.html {}
        end
      end
    end
  end
end

app/views/study/checklist.html.haml
=content_for :head do
  =stylesheet_link_tag "study"

=content_for :content do 
  .span-24.last
    %h2 Images of the City Study
    %p Please step through the following instructions for the appropriate day. As you complete the tasks, they will be checked off the list. If you have any questions or encounter problems, contact Drew Dara-Abrams (the experimenter) at any time: <a href="mailto:drew@geog.ucsb.edu">drew@geog.ucsb.edu</a> or (805) 680-7191.
    
    #day1.day
      - day = current_user.gave_consent
      %h2{:class => day.today? ? "current" : ""} Day #1 #{day.strftime("%A, %B %d, %Y")}
      
      %li.checked Informed Consent Form
      
      - if current_user.dissstudythree_demographics_questionnaire
        %li.checked Demographics Questionnaire
      - else
        %li= link_to "Demographics Questionnaire", study_demographics_path
        
      - if current_user.sbsod_record
        %li.checked Sense of Direction Questionnaire
      - else
        %li= link_to "Sense of Direction Questionnaire", study_sbsod_path
      
      - if current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0
        %li.checked
          <a href="/study/images_howto.html" target="_new">Read Introduction to Cognitive Surveyor</a> and Start Using Cognitive Surveyor 
          (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
          #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      - else
        %li <a href="/study/images_howto.html" target="_new">Read Introduction to Cognitive Surveyor</a> and Start Using Cognitive Surveyor
      
    #day2.day
      - day = current_user.gave_consent + 1.day
      %h2{:class => day.today? ? "current" : ""} Day #2 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)

    #day3.day
      - day = current_user.gave_consent + 2.days
      %h2{:class => day.today? ? "current" : ""} Day #3 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      
    #day4.day
      - day = current_user.gave_consent + 3.days
      %h2{:class => day.today? ? "current" : ""} Day #4 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      
    #day5.day
      - day = current_user.gave_consent + 4.days
      %h2{:class => day.today? ? "current" : ""} Day #5 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      
    #day6.day
      - day = current_user.gave_consent + 5.days
      %h2{:class => day.today? ? "current" : ""} Day #6 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      
    #day7.day
      - day = current_user.gave_consent + 6.days
      %h2{:class => day.today? ? "current" : ""} Day #7 #{day.strftime("%A, %B %d, %Y")}
      %li{:class => current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length > 0 ? "checked" : ""}
        Use Cognitive Surveyor 
        (#{pluralize(current_user.landmark_visits.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'landmark')} visited, 
        #{pluralize(current_user.direction_distance_estimates.where(:created_at => day.beginning_of_day..day.end_of_day).length, 'estimate')} made)
      
    - current_user.landmark_visits.where("created_at > ?", day.end_of_day).group_by { |lv| lv.created_at.to_date }.each_with_index do |day, index|
      .day
        %h2{:class => day[0].today? ? "current" : ""} Day ##{index + 8} #{day[0].strftime("%A, %B %d, %Y")}
        %li{:class => current_user.landmark_visits.where(:created_at => day[0].beginning_of_day..day[0].end_of_day).length > 0 ? "checked" : ""}
          Use Cognitive Surveyor 
          (#{pluralize(current_user.landmark_visits.where(:created_at => day[0].beginning_of_day..day[0].end_of_day).length, 'landmark')} visited, 
          #{pluralize(current_user.direction_distance_estimates.where(:created_at => day[0].beginning_of_day..day[0].end_of_day).length, 'estimate')} made)
    
    #final-day.day
      %h2 Final Day
      %p Now you finally have the chance to view all the data that you've contributed over the past week. The Cognitive Surveyor Explorer works best in the latest version of <a href="http://www.mozilla.com/en-US/firefox/">Mozilla Firefox</a> or <a href="http://chrome.google.com/">Google Chrome</a>. Please make sure you are using one of those Web browsers before opening the Explorer and completing the following three tasks:
      %ol
        - if current_user.landmarks.where(:familiarity_rating => nil).length == 0      
          %li.checked Rate your familiarity with each of your landmarks (there will be instructions on how to do this).
        - else
          %li Rate your familiarity with each of your landmarks (there will be instructions on how to do this).
        %li Check to make sure that your landmarks are named correctly and are in the appropriate locations. Please rename or move them if necessary.
        %li Take as long as you'd like to explore your results.
      %li= link_to "To complete these three tasks, open Cognitive Surveyor Explorer", viewer_main_path
        
      %p After you are finished exploring your results, please complete a final questionnaire.
      - if current_user.dissstudythree_final_questionnaire
        %li.checked Complete Final Questionnaire
      - else
        %li= link_to "Complete Final Questionnaire", study_final_path
    
=render :partial => 'layouts/base'

app/views/study/consent.html.haml
=content_for :head do
  =stylesheet_link_tag "study"

=content_for :content do
  .span-24.last
    - if current_user.participating_in_study == "images_own_phone"
      %h2 Consent Form: Phone Provided by Participant
    - elsif current_user.participating_in_study == "images_borrow_phone"
      %h2 Consent Form: Phone Provided by Experimenter
  
    %h3 Images of the City
  
    %p You are invited to participate in a research study of how people navigate and remember the layout of cities. This study is being conducted by Drew Dara-Abrams and Prof. Martin Raubal in the Department of Geography at the University of California, Santa Barbara. We ask that you read this form and ask any questions you may have before agreeing to be in the study. 
  
    %p The study uses Google Android smart-phones to measure people’s travel patterns and spatial knowledge. Participants will be asked to begin by completing a Web-based questionnaire (which should take approximately 10 minutes). For the following week, each participant will run a custom application called Cognitive Surveyor on their own Android phone. When arriving at a destination (home, office, grocery store, etc.), participants will use the application to record the destination as a landmark and to estimate the directions and distances toward their other previously recorded landmarks. This series of questions should not take long (likely 30 seconds to 2 minutes). Participants will be asked to repeat the procedure at each destination throughout the entire 7 days of the week. At the conclusion of the week, participants will be asked to complete another Web-based questionnaire (which will take no longer than 15 minutes). 

    %p The records of this study will be kept private. In any sort of report we might publish, we will not include any information that will make it possible to identify a participant. Research records will be encrypted for transmission and stored securely; only researchers will have access to the records. Your data will not be recorded together with your name, and any records that may uniquely identify you by name will be destroyed at the conclusion of the study.

    %p Participation in this study is entirely voluntary. If you decide to participate, you are free to not answer any question or to withdraw from the study at any time without penalty. Please feel free to contact the researchers:

    %p
      Drew Dara-Abrams<br/>
      (805) 680-7191<br/>
      drew@geog.ucsb.edu
    %p
      Prof. Martin Raubal<br/>
      (805) 280-1754<br/>
      raubal@geog.ucsb.edu
    
    %p The Human Subjects Committee at UCSB has reviewed and approved this study. You may also contact Kathy Graham, the committee’s coordinator, at (805) 893-3807 or graham@research.ucsb.edu with any questions or concerns.
  
    - if current_user.participating_in_study == "images_own_phone"
      %p For your participation in the study you will receive a $30 gift certificate to Amazon.com. If you decide to withdraw before completing the study, your gift certificate will be prorated by day.
    - elsif current_user.participating_in_study == "images_borrow_phone"
      %p For your participation in the study you will be able to use the smart-phone provided by the experimenter for domestic calls, text messages, and Internet access during the duration of the study. If you decide to withdraw before completing the study, you will be asked to return the phone at that time.

    %p Please let the experimenter know by phone or e-mail if you have any questions at this time. You may also ask questions at any later time.

    %p By clicking "I agree" you confirm that you are over 18 years old and that you are willing to participate in this study.
    
    %form(action="#{study_consent_path}" method="post")
      =submit_tag "I agree"
      
=render :partial => 'layouts/base'

app/views/study/demographics.html.haml
=content_for :head do
  =stylesheet_link_tag "study"

=content_for :content do
  .span-24.last
    =semantic_form_for(@dissstudythree_demographics_questionnaire, :url => study_demographics_path) do |f|
      =f.inputs "Demographics Questionnaire" do
        =f.input :age, :input_html => { :size => 3 }
        =f.input :sex, :as => :select, :collection => ['female', 'male']
        =f.input :years_in_current_region, :input_html => { :size => 3 }, :label => "How many years have you lived in your current city/metro region?"
        =f.input :primary_mode_of_transportation, :as => :select, :collection => ['car', 'foot', 'bus', 'bike', 'train'], :label => "What is your primary mode of transportation?"
        =f.input :phone_model, :label => "What model of Android smart-phone are you using?"
        =f.input :months_with_a_smartphone, :input_html => { :size => 3 }, :label => "For approximately how many months have you used a smart-phone?"
        =f.input :smartphone_skill_rating, :as => :select, :collection => [1,2,3,4,5], :label => "On a scale of 1 (beginner) to 5 (expert), how would you rate your level of experience using your smart-phone?"
      =f.buttons do
        =f.commit_button "Done"
  
=render :partial => 'layouts/base'

app/views/study/final.html.haml
=content_for :head do
  =stylesheet_link_tag "study"

=content_for :content do
  .span-24.last
    =semantic_form_for(@dissstudythree_final_questionnaire, :url => study_final_path) do |f|
      =f.inputs "Final Questionnaire" do
        =f.input :lbs_use, :label => "During the past week, how often did you use your smart-phone for maps, directions, and/or navigation assistance? Did you use any other sorts of location-based services on your smart-phone?"
        =f.input :attention_to_surroundings, :label => "While using Cognitive Surveyor, did you pay more (or less) attention than normal to your surroundings? If so, how?"
        =f.input :affect_travel, :label => "Did using Cognitive Surveyor affect any of your travel patterns or decisions during the past week? If so, how?"
        =f.input :revealing, :label => "Was it revealing to see your landmarks, visits, and estimates mapped in the Web-based explorer? If so, how?"
        =f.input :features, :label => "Any particular features of the Cognitive Surveyor mobile application or the Web-based explorer that you found especially interesting/frustrating/suggestive/boring/etc.?"
        =f.input :comments_questions, :label => "Any other comments or questions?"
      =f.buttons do
        =f.commit_button "Done"
  
=render :partial => 'layouts/base'

app/views/study/sbsod.html.haml
-items = []
-items << {'n' => 'q1', 'q' => 'I am very good at giving directions.'}
-items << {'n' => 'q2', 'q' => 'I have a poor memory for where I left things.'}
-items << {'n' => 'q3', 'q' => 'I am very good at judging distances.'}
-items << {'n' => 'q4', 'q' => 'My "sense of direction" is very good.'}
-items << {'n' => 'q5', 'q' => 'I tend to think of my environment in terms of cardinal directions (N, S, E, W).'}
-items << {'n' => 'q6', 'q' => 'I very easily get lost in a new city.'}
-items << {'n' => 'q7', 'q' => 'I enjoy reading maps.'}
-items << {'n' => 'q8', 'q' => 'I have trouble understanding directions.'}
-items << {'n' => 'q9', 'q' => 'I am very good at reading maps.'}
-items << {'n' => 'q10', 'q' => "I don't remember routes very well while riding as a passenger in a car."}
-items << {'n' => 'q11', 'q' => "I don't enjoy giving directions."}
-items << {'n' => 'q12', 'q' => "It's not important to me to know where I am."}
-items << {'n' => 'q13', 'q' => 'I usually let someone else do the navigational planning for long trips.'}
-items << {'n' => 'q14', 'q' => 'I can usually remember a new route after I have traveled it only once.'}
-items << {'n' => 'q15', 'q' => 'I don\'t have a very good "mental map" of my environment.'}

=content_for :head do
  =stylesheet_link_tag "study"
  :css
    label.missing {
      background: #8A0917;
      color: #FFFFFF;
      padding: 6px;
      display: none;
    }
    fieldset {
      border: 0;
    }
    fieldset li {
      list-style: none;
      float: left;
      width: 1em;
      text-align: center;
      padding-right: 40px;
    }
    input {
      margin: 0;
    }
    table {
      width: auto;
    }

=content_for :content do
  .span-24.last
    %h2 Santa Barbara Sense of Direction Scale
    %p This questionnaire consists of several statements about your spatial and navigational abilities, preferences, and experiences. After each statement, you should select a number to indicate your level of agreement with the statement. Select "1" if you strongly agree that the statement applies to you, "7" if you strongly disagree, or some number in between if your agreement is intermediate. Select "4" if you neither agree nor disagree.

    =semantic_form_for @sbsod_record, :url => study_sbsod_path, :html => {:id => "sbsod_form", :name => "sbsod_form"} do |f|
      -for item in items
        %p{:id => "p_" + item["n"]}
          %strong= item["q"]
          %table(border="0")
            %tr
              %td strongly agree
              %td= f.input "#{item['n']}", :as => :radio, :collection => [1,2,3,4,5,6,7], :label => ''
              %td strongly disagree

      %p(align="center")= submit_tag 'I am Finished', :class => "button"

=render :partial => 'layouts/base'